version: '3.8'

services:
  cryomamba-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - LOG_LEVEL=INFO
      - CORS_ORIGINS=["http://localhost:3000", "http://localhost:8080"]
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
